# Assignment 1 Questions #
#### CSCI 4831 - Sabermetrics ####
#### Instructor: Hoenigman ####
#### Due: Wednesday, Jan 23 by 3pm ####

Name: Michael Dresser

**Using the Lahman data, answer the following questions in a Jupyter Notebook. Submit your notebook to the Assignment 1 link on Canvas.**

1. (10 pts) Which player had the most at-bats in either league in 2015?

In [1]:
import pybaseball.lahman as lahman

lahman.download_lahman()

In [12]:
batting = lahman.batting()
batting_2015 = batting.loc[(batting.yearID == 2015)]
batting_2015.head()
max_ab_index = batting_2015["AB"].idxmax()

print(batting_2015.loc[max_ab_index].playerID)

altuvjo01

2. (10 pts) Which team grounded into the most double plays in 2016?

In [38]:
batting_2016 = batting.loc[(batting.yearID == 2016)]
batting_2016.columns
batting_2016_team_GIDP = batting_2016.loc[:, ["teamID", "GIDP"]]
GIDP_by_team = batting_2016_team_GIDP.groupby("teamID").sum()
GIDP_by_team.loc[GIDP_by_team["GIDP"].idxmax()]

GIDP    153.0
Name: TOR, dtype: float64

3. (10 pts) Which team scored the most total runs between 2010-2016?

In [18]:
teams = lahman.teams()
teams_range = teams.loc[(teams["yearID"] >= 2010) & (teams["yearID"] <= 2016)]
teams_range_runs = teams_range.loc[:, ["teamID", "R"]]
teams_range_runs.loc[teams_range_runs["R"].idxmax()].teamID

'TOR'

4. (10 pts) Which pitcher had the lowest ERA in 2012 and pitched at least 50 innings?

In [25]:
pitching = lahman.pitching()
pitching_2012_50plus = pitching.loc[(pitching["yearID"] == 2012) & (pitching["IPouts"] >= 50)]
pitching_2012_50plus.loc[pitching_2012_50plus["ERA"].idxmin()].playerID

'rodnefe01'

The Mendoza Line is a baseball expression named after shortstop Mario Mendoza, whose batting average through most of his career has been adopted to define the threshold needed for a player to remain in Major League Baseball. When a position player's batting average falls below .200, the player is said to be 'below the Mendoza Line'. This is often thought of as the offensive threshold below which a player's presence in Major League Baseball cannot be justified, regardless of his defensive abilities. The term has been adopted in other contexts as well when one is so incompetent in one key skill that other skills cannot compensate for that deficiency, e.g. Professor X's FCQ scores are below the Mendoza Line. 

5. (20 pts) Create a dataframe of all position players - not pitchers - with a batting average (BA) below the Mendoza Line since 2010. Your dataframe needs to include the player's playerID, first name, last name, team name, position, BA, and AB. If a player had multiple teams in 2010, you can include both teams as a separate line in the dataframe.

In [58]:
import pandas as pd
fielding = lahman.fielding()
master = lahman.master()
names = master.loc[:, ["playerID", "nameFirst", "nameLast"]]

position_players = fielding.loc[(fielding["POS"] != "P") &
                                (fielding["yearID"] > 2010)]

players_with_batting = pd.merge(position_players, batting, how="inner", 
                                left_on=["playerID", "yearID", "teamID"],
                                right_on=["playerID", "yearID", "teamID"])
players_with_batting["BA"] = players_with_batting["H"] / players_with_batting["AB"]

players_with_batting = pd.merge(players_with_batting, names, how="inner",
                               left_on=["playerID"], right_on=["playerID"])

mendoza_players = players_with_batting.loc[players_with_batting["BA"] < 0.2]
mendoza_players = mendoza_players.loc[:, ["playerID", "nameFirst", "nameLast",
                                                   "teamID", "POS", "BA", "AB"]]
mendoza_players.sort_values(by=["playerID"], inplace=True)
mendoza_players

       playerID  nameFirst   nameLast teamID POS        BA   AB
4502  abreuto01       Tony      Abreu    SFN  3B  0.000000    4
4501  abreuto01       Tony      Abreu    SFN  2B  0.000000    4
17    ackledu01     Dustin     Ackley    NYA  1B  0.147541   61
18    ackledu01     Dustin     Ackley    NYA  2B  0.147541   61
19    ackledu01     Dustin     Ackley    NYA  OF  0.147541   61
5764  adamecr01  Cristhian     Adames    COL  SS  0.066667   15
5763  adamecr01  Cristhian     Adames    COL  2B  0.066667   15
5234  adamsda02      David      Adams    NYA  2B  0.192857  140
5233  adamsda02      David      Adams    NYA  1B  0.192857  140
5235  adamsda02      David      Adams    NYA  3B  0.192857  140
5770  adamsla01       Lane      Adams    KCA  OF  0.000000    3
5238  adducji02        Jim     Adduci    TEX  1B  0.168317  101
5239  adducji02        Jim     Adduci    TEX  OF  0.168317  101
5246  adriaeh01      Ehire   Adrianza    SFN  3B  0.185841  113
5247  adriaeh01      Ehire   Adrianza    SFN  SS  0.185841  113
5244  adriaeh01      Ehire   Adrianza    SFN  1B  0.185841  113
5245  adriaeh01      Ehire   Adrianza    SFN  2B  0.185841  113
5774  aguilje01      Jesus    Aguilar    CLE  1B  0.000000    6
5772  aguilje01      Jesus    Aguilar    CLE  3B  0.121212   33
5771  aguilje01      Jesus    Aguilar    CLE  1B  0.121212   33
6216  alberha01     Hanser    Alberto    TEX  3B  0.142857   56
6215  alberha01     Hanser    Alberto    TEX  2B  0.142857   56
6217  alberha01     Hanser    Alberto    TEX  SS  0.142857   56
6214  alberha01     Hanser    Alberto    TEX  1B  0.142857   56
5781  alcanar01  Arismendy  Alcantara    CHN  2B  0.076923   26
5782  alcanar01  Arismendy  Alcantara    CHN  3B  0.076923   26
6511  alfarjo01      Jorge     Alfaro    PHI   C  0.125000   16
25    allenbr01    Brandon      Allen    TBA  OF  0.153846   13
24    allenbr01    Brandon      Allen    OAK  1B  0.000000    7
22    allenbr01    Brandon      Allen    ARI  1B  0.172414   29
...         ...        ...        ...    ...  ..       ...  ...
4347  wilsobo02      Bobby     Wilson    LAA   C  0.189189  111
4351  wilsobo02      Bobby     Wilson    TBA   C  0.145455   55
4362  wilsoja02       Jack     Wilson    ATL  SS  0.169014   71
4361  wilsoja02       Jack     Wilson    ATL  2B  0.169014   71
4378  wilsomi02       Mike     Wilson    SEA  OF  0.148148   27
4380   wisede01    Dewayne       Wise    TOR  OF  0.125000   32
5747   wongko01     Kolten       Wong    SLN  2B  0.152542   59
4385   woodbr01    Brandon       Wood    LAA  SS  0.142857   14
4384   woodbr01    Brandon       Wood    LAA  1B  0.142857   14
6686   woodtr01     Travis       Wood    CHN  OF  0.181818   11
4390  woodwch01      Chris   Woodward    TOR  2B  0.000000   10
4391  woodwch01      Chris   Woodward    TOR  3B  0.000000   10
4392  woodwch01      Chris   Woodward    TOR  SS  0.000000   10
4403  worthda01      Danny      Worth    HOU  3B  0.179487   39
4398  worthda01      Danny      Worth    DET  3B  0.000000    2
4399  worthda01      Danny      Worth    DET  1B  0.166667   42
4400  worthda01      Danny      Worth    DET  2B  0.166667   42
4401  worthda01      Danny      Worth    DET  SS  0.166667   42
4402  worthda01      Danny      Worth    HOU  2B  0.179487   39
4404  worthda01      Danny      Worth    HOU  SS  0.179487   39
4414  wrighwe01     Wesley     Wright    HOU  OF  0.000000    2
4413  wrighwe01     Wesley     Wright    HOU  OF  0.000000    1
6210   ynoara01     Rafael       Ynoa    COL  OF  0.000000    5
4446  younger03       Eric      Young    ATL  OF  0.168831   77
4447  younger03       Eric      Young    NYN  OF  0.000000    8
4448  younger03       Eric      Young    NYA  OF  0.000000    1
4450  youngma02       Matt      Young    DET  2B  0.100000   10
4451  youngma02       Matt      Young    DET  OF  0.100000   10
5758  zuninmi01       Mike     Zunino    SEA   C  0.174286  350
5757  zuninmi01       Mike     Zunino    SEA   C  0.198630  438

[1414 rows x 7 columns]

6. (40 pts) Your friend, who thinks he knows so much about baseball, is talking on at length about how the pitcher who starts the All-star game is always the best pitcher in the league. Make the case that your friend is wrong. Is it true that the All-star starters are the best pitchers? What are the criteria that determine "best"? Could different criteria produce a different answer? 

To answer this question, you need to provide a written explanation that is about one page in length that describes how you define who is the best pitcher, and how the best pitcher compares to the All-star pitcher and other pitchers in the league. You need to use more than one metric for evaluating pitchers. Your answer also needs to include the data, and the code you write to generate that data, to support your explanation.

In [106]:
allstarpitchers = lahman.all_star_full()
pitching = lahman.pitching()

In [101]:
normal_ipouts = pitching["IPouts"].quantile(.66)
pitching = pitching.loc[pitching["IPouts"] > normal_ipouts]
pitching = pitching.loc[(pitching["yearID"] >= 1995),
                        ["playerID", "yearID", "teamID", "ERA", "BAOpp"]]

In [104]:
pitching.sort_values(by=["yearID", "ERA", "BAOpp"], ascending=[True, True, True], inplace=True)
pitching_by_year = pitching.groupby("yearID")
top_2_pitchers = pitching_by_year.head(2)
top_2_pitchers

        playerID  yearID teamID   ERA  BAOpp
30155  maddugr01    1995    ATL  1.63  0.190
30398  veresda01    1995    HOU  2.26  0.220
30521  brownke01    1996    FLO  1.89  0.200
30893  riverma01    1996    NYA  2.09  0.170
31366  martipe02    1997    MON  1.90  0.180
31148  clemero02    1997    TOR  2.05  0.210
31939  maddugr01    1998    ATL  2.22    NaN
31698  brownke01    1998    SDN  2.38    NaN
32577  martipe02    1999    BOS  2.07  0.000
32429  foulkke01    1999    CHA  2.22  0.000
33230  martipe02    2000    BOS  1.74  0.167
32970  brownke01    2000    LAN  2.58  0.213
33906  martipe02    2001    BOS  2.39  0.199
33837  johnsra05    2001    ARI  2.49  0.203
34365  doteloc01    2002    HOU  1.85  0.173
34570  martipe02    2002    BOS  2.26  0.198
35279   motagu01    2003    LAN  1.97  0.206
35244  martipe02    2003    BOS  2.22  0.215
35915  lidgebr01    2004    HOU  1.90  0.174
36031  peavyja01    2004    SDN  2.27  0.236
36359  clemero02    2005    HOU  1.87  0.198
36691  pettian01    2005    HOU  2.39  0.230
37243  liriafr01    2006    MIN  2.16  0.205
37011  clemero02    2006    HOU  2.30  0.216
37636   bellhe01    2007    SDN  2.02  0.185
38078  peavyja01    2007    SDN  2.54  0.208
38872  sabatcc01    2008    MIL  1.65  0.222
38886  santajo01    2008    NYN  2.53  0.232
39255  greinza01    2009    KCA  2.16  0.230
39127  carpech01    2009    SLN  2.24  0.226
39993  hernafe02    2010    SEA  2.27  0.212
40031  johnsjo09    2010    FLO  2.30  0.229
40752  kershcl01    2011    LAN  2.28  0.207
40570  cuetojo01    2011    CIN  2.31  0.220
41568  medlekr01    2012    ATL  1.57  0.208
41309  dempsry01    2012    CHN  2.25  0.210
41934  buchhcl01    2013    BOS  1.74  0.199
42203  kershcl01    2013    LAN  1.83  0.195
42935  kershcl01    2014    LAN  1.77  0.196
42881  hernafe02    2014    SEA  2.14  0.200
43619  greinza01    2015    LAN  1.66  0.187
43355  arrieja01    2015    CHN  1.77  0.185
44520  kershcl01    2016    LAN  1.69  0.184
44460  hendrky01    2016    CHN  2.13  0.207

In [103]:
allstarpitchers = allstarpitchers.loc[(allstarpitchers["yearID"] >= 1995) & 
                                      (allstarpitchers["startingPos"] == 1.0)]
allstarpitchers

       playerID  yearID  gameNum        gameID teamID lgID   GP  startingPos
3608  johnsra05    1995        0  ALS199507110    SEA   AL  1.0          1.0
3638   nomohi01    1995        0  ALS199507110    LAN   NL  1.0          1.0
3669   nagych01    1996        0  NLS199607090    CLE   AL  1.0          1.0
3698  smoltjo01    1996        0  NLS199607090    ATL   NL  1.0          1.0
3728  johnsra05    1997        0  ALS199707080    SEA   AL  1.0          1.0
3758  maddugr01    1997        0  ALS199707080    ATL   NL  1.0          1.0
3789  wellsda01    1998        0  NLS199807070    NYA   AL  1.0          1.0
3821  maddugr01    1998        0  NLS199807070    ATL   NL  1.0          1.0
3852  martipe02    1999        0  ALS199907130    BOS   AL  1.0          1.0
3884  schilcu01    1999        0  ALS199907130    PHI   NL  1.0          1.0
3916  wellsda01    2000        0  NLS200007110    TOR   AL  1.0          1.0
3950  johnsra05    2000        0  NLS200007110    ARI   NL  1.0          1.0
3985  clemero02    2001        0  ALS200107100    NYA   AL  1.0          1.0
4017  johnsra05    2001        0  ALS200107100    ARI   NL  1.0          1.0
4048   lowede01    2002        0  NLS200207090    BOS   AL  1.0          1.0
4079  schilcu01    2002        0  NLS200207090    ARI   NL  1.0          1.0
4112  loaizes01    2003        0  ALS200307150    CHA   AL  1.0          1.0
4147  schmija01    2003        0  ALS200307150    SFN   NL  1.0          1.0
4182  muldema01    2004        0  NLS200407130    OAK   AL  1.0          1.0
4216  clemero02    2004        0  NLS200407130    HOU   NL  1.0          1.0
4250  buehrma01    2005        0  ALS200507120    CHA   AL  1.0          1.0
4283  carpech01    2005        0  ALS200507120    SLN   NL  1.0          1.0
4318  rogerke01    2006        0  NLS200607110    DET   AL  1.0          1.0
4354  pennybr01    2006        0  NLS200607110    LAN   NL  1.0          1.0
4389  harenda01    2007        0  NLS200707100    OAK   AL  1.0          1.0
4421  peavyja01    2007        0  NLS200707100    SDN   NL  1.0          1.0
4455    leecl02    2008        0  ALS200807150    CLE   AL  1.0          1.0
4488  sheetbe01    2008        0  ALS200807150    MIL   NL  1.0          1.0
4522  hallaro01    2009        0  NLS200907140    TOR   AL  1.0          1.0
4558  linceti01    2009        0  NLS200907140    SFN   NL  1.0          1.0
4594  priceda01    2010        0  ALS201007130    TBA   AL  1.0          1.0
4636  jimenub01    2010        0  ALS201007130    COL   NL  1.0          1.0
4677  weaveje02    2011        0  NLS201107120    DET   AL  1.0          1.0
4720  hallaro01    2011        0  NLS201107120    PHI   NL  1.0          1.0
4761  verlaju01    2012        0  ALS201207100    DET   AL  1.0          1.0
4797   cainma01    2012        0  ALS201207100    SFN   NL  1.0          1.0
4835  scherma01    2013        0  NLS201307160    DET   AL  1.0          1.0
4875  harvema01    2013        0  NLS201307160    NYN   NL  1.0          1.0
4913  hernafe02    2014        0  ALS201407150    SEA   AL  1.0          1.0
4953  utleych01    2014        0  ALS201407150    PHI   NL  1.0          1.0
4995  keuchda01    2015        0  NLS201507140    HOU   AL  1.0          1.0
5030  greinza01    2015        0  NLS201507140    LAN   NL  1.0          1.0
5099   salech01    2016        0  ALS201607120    CHA   AL  1.0          1.0
5113  cuetojo01    2016        0  ALS201607120    SFN   NL  1.0          1.0

I chose two simple criteria to evaluate pitchers: ERA and BAOpp, sorting first by ERA. I only considered pitchers from 1995 onward to simplify the number of comparisons. I also only considered pitchers in the 0.66 quantile of IPouts because I only wanted to consider pitchers who had pitched consistently throughout the season.

We can see that in 2016, 2013, 2012, 2011, 2010, and 2009 (among others) neither of the two pitchers that appear in my top two for that year started the all star game. This is good evidence against my friend. Naturally the top pitchers in every year would change if the criteria were to change, but I think the point would still stand because 5 years in a row (possibly more) do not hold up by my metric.