# Introduction to pyBaseball

Name: Michael Dresser

For the first part of this class, we'll use the pyBaseball package to access data. pyBaseball is a python package that provides a nice API for the Baseball Savant website and the Lahman database. Lahman is actually a bunch of .csv files that you download onto your local machine.

There are lots of examples of pyBaseball queries on their github repo. I encourage you to rummage through the site and look at what's available. 

If you haven't already done so, you need to install pyBaseball.

Open a terminal and type the following commands to pull the latest pybaseball

* git clone https://github.com/jldbc/pybaseball
* cd pybaseball
* python setup.py install --user

To test that pybaseball installed correctly, run the following. If you get back data, pybaseball is working.

In [1]:
from pybaseball import statcast
data = statcast(start_dt='2017-06-24', end_dt='2017-06-27')
data.head(2)

,index,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,316,CU,2017-06-27,79.7,-1.3441,5.4075,Matt Bush,608070.0,456713.0,field_out,...,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,Standard,Strategic
1,329,FF,2017-06-27,98.1,-1.3547,5.4196,Matt Bush,429665.0,456713.0,field_out,...,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,Standard,Strategic

## Lahman Database ##
The Lahman database was created by Sean Lahman, and contains pitching, hitting, and fielding statistics for Major League Baseball from 1871 through 2017.  It includes data from the American and National Leagues, as well as other leagues from 1871-1875. 

The version that we will work with here is a collection of .csv files. The files are all publicly available through several sources, including http://www.seanlahman.com. We're going to access it through the pybaseball Python package. You can find documentation on what's in each .csv on the Lahman website.

A quick query of pybaseball Lahman to display some data

In [16]:
#Download the Lahman data
import pybaseball.lahman as lahman

#download the entire lahman database to your current working directory
lahman.download_lahman() 

#Look at the data. Divided by category
#.csv files for Batting, Fielding, Managers, Pitching, etc

## Dataframe ##
A dataframe in Python is a 2d data structure with rows and columns. Think of dataframes as data tables where each row is an observation and each column is a feature of the observation.

In the Lahman database, we can access create a dataframe from the Batting.csv file. Once we create the dataframe, we should look at it:

In [18]:
batting = lahman.batting()
#first, inspect the data
#get the first 10 rows
batting.head(10)

#or, to show the column headers only

list(batting)

['playerID',
 'yearID',
 'stint',
 'teamID',
 'lgID',
 'G',
 'AB',
 'R',
 'H',
 '2B',
 '3B',
 'HR',
 'RBI',
 'SB',
 'CS',
 'BB',
 'SO',
 'IBB',
 'HBP',
 'SH',
 'SF',
 'GIDP']

### Things to do with dataframes ###
It's rare that we want to use all of the data that we have in our dataframe. More likely, you'll want to pull out certain rows and columns that you can use to answer interesting questions.

#### Filter rows ####
Access the rows in the dataframe using the column name and set criteria for the values in those columns. For example, to pull out the 2016 data out of the batting dataframe:

In [19]:
batting2016 = batting.loc[(batting["yearID"]==2016)]#one year only
batting2016.head(5)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
101333,abadfe01,2016,1,MIN,AL,39,1,0,0,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
101334,abadfe01,2016,2,BOS,AL,18,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
101335,abreujo02,2016,1,CHA,AL,159,624,67,183,32,...,100.0,0.0,2.0,47,125.0,7.0,15.0,0.0,9.0,21.0
101336,achteaj01,2016,1,LAA,AL,27,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
101337,ackledu01,2016,1,NYA,AL,28,61,6,9,0,...,4.0,0.0,0.0,8,9.0,0.0,0.0,0.0,1.0,0.0

#### Filter columns ####
If you only want to see certain columns in the dataframe, you can pull just those columns:

In [20]:
batting.loc[:,["teamID", "lgID"]].head(10)
#or filter rows and select columns
batting2016 = batting.loc[(batting["yearID"]==2016),["teamID", "lgID"]]
batting2016.head(10)

       teamID lgID
101333    MIN   AL
101334    BOS   AL
101335    CHA   AL
101336    LAA   AL
101337    NYA   AL
101338    COL   NL
101339    CLE   AL
101340    SLN   NL
101341    CIN   NL
101342    SFN   NL

### Another dataframe example ###
If you look at the pyBaseball Lahman.py code, you'll see the functions that return the data stored in each csv. For example, you can get information about different ballparks by looking at the Parks data in Parks.csv.

In [21]:
parks = lahman.parks()
parks.head(10)
p = parks.loc[(parks["park.name"]=='Riverside Park')]
print(p)

  park.key       park.name park.alias    city state country
0    ALB01  Riverside Park        NaN  Albany    NY      US

#### Dataframes in memory ####
In all of these examples, we created new variables that point to the original dataframe in memory. If you change a dataframe, it changes it everywhere that it is referenced. If you want to make changes, you should copy the dataframe first.

#### For more information about .loc, .iloc, and indexing ####
Here is a good article about accessing rows in a dataframe: <a href="https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix" target="_blank">Accessing data in a dataframe</a>

## Questions ##
1. Generate a dataframe of all players who played second base in 2010.
2. Generate a dataframe of all pitchers with an ERA < 4.0 since 2010.

In [23]:
fielding = lahman.fielding()
fielding_2B_2010 = fielding.loc[(fielding.POS == "2B") & (fielding.yearID == 2010)]
fielding_2B_2010.head()

,playerID,yearID,stint,teamID,lgID,POS,G,GS,InnOuts,PO,A,E,DP,PB,WP,SB,CS,ZR
123860,abreuto01,2010,1,ARI,NL,2B,12,11.0,265.0,16,18.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN
123881,andinro01,2010,1,BAL,AL,2B,8,5.0,150.0,6,10.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
123889,ariasjo01,2010,1,TEX,AL,2B,25,16.0,449.0,27,45.0,1.0,13.0,NaN,NaN,NaN,NaN,NaN
123891,ariasjo01,2010,2,NYN,NL,2B,13,4.0,158.0,19,13.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN
123902,avilemi01,2010,1,KCA,AL,2B,87,86.0,2267.0,183,258.0,11.0,40.0,NaN,NaN,NaN,NaN,NaN

In [25]:
pitching = lahman.pitching()
pitching_era = pitching.loc[(pitching.ERA < 4) & (pitching.yearID > 2010)]
pitching_era

,playerID,yearID,stint,teamID,lgID,W,L,G,GS,CG,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
40430,abreuju01,2011,1,HOU,NL,0,0,7,0,0,...,0.0,0.0,5.0,0,34.0,2.0,2,0.0,0.0,0.0
40432,aceveal01,2011,1,BOS,AL,10,2,55,4,0,...,1.0,1.0,15.0,2,474.0,15.0,37,3.0,3.0,9.0
40433,acostma01,2011,1,NYN,NL,4,1,44,0,0,...,0.0,0.0,2.0,0,204.0,15.0,21,0.0,1.0,3.0
40434,adamsmi03,2011,1,SDN,NL,3,1,48,0,0,...,1.0,0.0,0.0,0,179.0,5.0,7,1.0,1.0,1.0
40435,adamsmi03,2011,2,TEX,AL,2,3,27,0,0,...,1.0,0.0,0.0,0,98.0,5.0,6,1.0,0.0,1.0
40437,affelje01,2011,1,SFN,NL,3,2,67,0,0,...,3.0,4.0,4.0,0,259.0,12.0,22,4.0,0.0,4.0
40439,albural01,2011,1,DET,AL,6,1,41,0,0,...,4.0,4.0,2.0,0,182.0,11.0,9,2.0,1.0,0.0
40440,alvarhe01,2011,1,TOR,AL,1,3,10,10,0,...,0.0,2.0,4.0,0,259.0,0.0,26,1.0,2.0,7.0
40442,arredjo01,2011,1,CIN,NL,4,4,53,0,0,...,5.0,4.0,2.0,2,226.0,10.0,21,3.0,0.0,6.0
40446,atchisc01,2011,1,BOS,AL,1,0,17,0,0,...,0.0,2.0,2.0,0,122.0,4.0,11,1.0,2.0,5.0
40449,axelrdy01,2011,1,CHA,AL,1,0,4,3,0,...,2.0,0.0,1.0,0,82.0,1.0,6,0.0,2.0,2.0
40450,axforjo01,2011,1,MIL,NL,2,2,74,0,0,...,1.0,8.0,0.0,0,305.0,63.0,19,1.0,1.0,4.0
40451,ayalalu01,2011,1,NYA,AL,2,2,52,0,0,...,3.0,2.0,6.0,1,233.0,20.0,17,4.0,4.0,10.0
40454,bailean01,2011,1,OAK,AL,0,4,42,0,0,...,2.0,0.0,0.0,0,170.0,37.0,18,1.0,1.0,3.0
40456,bakersc02,2011,1,MIN,AL,8,6,23,21,1,...,2.0,4.0,4.0,0,548.0,2.0,50,1.0,2.0,9.0
40458,balfogr01,2011,1,OAK,AL,5,2,62,0,0,...,1.0,0.0,0.0,0,242.0,15.0,17,1.0,0.0,8.0
40459,bardda01,2011,1,BOS,AL,2,9,70,0,0,...,3.0,2.0,2.0,1,288.0,10.0,29,5.0,0.0,1.0
40460,bassan01,2011,1,SDN,NL,2,0,27,3,0,...,1.0,1.0,1.0,0,198.0,6.0,9,2.0,0.0,7.0
40461,bastaan01,2011,1,PHI,NL,6,1,64,0,0,...,0.0,4.0,0.0,0,225.0,15.0,17,2.0,2.0,4.0
40463,batismi01,2011,2,NYN,NL,2,0,9,4,1,...,1.0,1.0,2.0,0,125.0,0.0,9,2.0,1.0,6.0
40464,beachbr01,2011,1,ATL,NL,7,3,25,25,0,...,9.0,11.0,5.0,1,591.0,0.0,62,6.0,5.0,6.0
40467,beckch01,2011,1,TOR,AL,0,0,3,0,0,...,0.0,0.0,0.0,0,8.0,3.0,0,0.0,0.0,0.0
40468,beckejo02,2011,1,BOS,AL,13,7,30,30,1,...,1.0,6.0,9.0,0,767.0,0.0,65,8.0,5.0,14.0
40469,bedarer01,2011,1,SEA,AL,4,7,16,16,0,...,0.0,5.0,1.0,0,373.0,0.0,41,1.0,0.0,8.0
40472,belisma01,2011,1,COL,NL,10,4,74,0,0,...,3.0,2.0,4.0,0,301.0,10.0,33,4.0,0.0,8.0
40473,bellhe01,2011,1,SDN,NL,3,4,64,0,0,...,2.0,8.0,0.0,0,256.0,54.0,20,5.0,1.0,6.0
40474,belltr01,2011,1,LAA,AL,1,1,19,0,0,...,1.0,2.0,1.0,0,146.0,14.0,14,0.0,1.0,3.0
40476,benoijo01,2011,1,DET,AL,4,3,66,0,0,...,1.0,3.0,2.0,0,241.0,13.0,22,1.0,5.0,6.0
40478,bergju01,2011,1,CHN,NL,0,0,8,0,0,...,1.0,0.0,2.0,0,52.0,0.0,5,0.0,0.0,2.0
40481,betanra01,2011,1,COL,NL,2,0,68,0,0,...,0.0,1.0,0.0,2,237.0,24.0,21,0.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44884,tillmch01,2016,1,BAL,AL,16,6,30,30,0,...,1.0,9.0,7.0,0,715.0,0.0,73,2.0,4.0,20.0
44889,torreca01,2016,1,MIL,NL,3,3,72,0,0,...,3.0,1.0,4.0,1,339.0,12.0,26,3.0,2.0,6.0
44890,torrejo02,2016,1,SDN,NL,0,0,4,0,0,...,0.0,1.0,0.0,0,14.0,1.0,0,0.0,0.0,0.0
44891,treinbl01,2016,1,WAS,NL,4,1,73,0,0,...,6.0,1.0,0.0,0,263.0,17.0,19,2.0,2.0,17.0
44893,tropeni01,2016,1,LAA,AL,3,2,13,13,0,...,1.0,4.0,2.0,0,296.0,0.0,27,1.0,3.0,4.0
44897,ueharko01,2016,1,BOS,AL,2,3,50,0,0,...,1.0,1.0,2.0,0,184.0,12.0,18,1.0,0.0,2.0
44899,uriasju01,2016,1,LAN,NL,5,2,18,15,0,...,0.0,3.0,4.0,0,336.0,1.0,32,4.0,1.0,6.0
44902,vargaja01,2016,1,KCA,AL,0,0,3,3,0,...,0.0,0.0,0.0,0,47.0,0.0,3,0.0,0.0,0.0
44908,verlaju01,2016,1,DET,AL,16,9,34,34,2,...,1.0,6.0,8.0,0,903.0,0.0,81,4.0,7.0,8.0
44911,vinceni01,2016,1,SEA,AL,4,4,60,0,0,...,5.0,0.0,1.0,0,247.0,15.0,26,1.0,1.0,4.0
44916,wagnety01,2016,1,ARI,NL,1,0,3,0,0,...,0.0,0.0,0.0,0,40.0,0.0,3,0.0,0.0,1.0
44921,warread01,2016,2,NYA,AL,4,2,29,0,0,...,2.0,3.0,1.0,0,125.0,3.0,13,1.0,1.0,2.0
44922,watsoto01,2016,1,PIT,NL,2,5,70,0,0,...,1.0,0.0,3.0,0,272.0,27.0,26,4.0,3.0,9.0
44925,webbda01,2016,1,CHA,AL,0,0,1,0,0,...,0.0,0.0,0.0,0,6.0,1.0,0,0.0,0.0,0.0
44931,whitlch01,2016,1,TBA,AL,0,0,5,1,0,...,0.0,0.0,0.0,0,61.0,0.0,7,0.0,0.0,0.0
44934,wilheto01,2016,2,SEA,AL,0,1,29,0,0,...,0.0,0.0,0.0,0,100.0,2.0,10,0.0,0.0,4.0
44937,wilsoal01,2016,1,DET,AL,4,0,62,0,0,...,5.0,2.0,1.0,0,297.0,6.0,26,0.0,5.0,8.0
44941,winklda01,2016,1,ATL,NL,0,0,3,0,0,...,0.0,0.0,0.0,0,8.0,0.0,0,0.0,0.0,0.0
44943,withrch01,2016,1,ATL,NL,3,0,46,0,0,...,1.0,1.0,2.0,0,158.0,6.0,16,2.0,1.0,2.0
44944,wittgni01,2016,1,MIA,NL,4,3,48,0,0,...,2.0,1.0,1.0,0,213.0,9.0,18,3.0,2.0,2.0
44945,woodal02,2016,1,LAN,NL,1,4,14,10,0,...,0.0,4.0,3.0,0,255.0,0.0,30,0.0,2.0,5.0
44946,woodbl01,2016,1,CIN,NL,6,5,70,0,0,...,3.0,8.0,2.0,0,330.0,21.0,38,1.0,2.0,8.0
44947,woodtr01,2016,1,CHN,NL,4,0,77,0,0,...,2.0,0.0,1.0,0,252.0,16.0,24,1.0,0.0,3.0
44948,worleva01,2016,1,BAL,AL,2,2,35,4,0,...,0.0,3.0,3.0,0,365.0,13.0,37,0.0,3.0,12.0
44952,wrighst01,2016,1,BOS,AL,13,6,24,24,4,...,1.0,10.0,8.0,0,656.0,0.0,74,2.0,2.0,16.0
44955,ynoami01,2016,1,CHA,AL,1,0,23,0,0,...,2.0,4.0,5.0,0,135.0,7.0,11,1.0,2.0,1.0
44958,zastrro01,2016,1,CHN,NL,1,0,8,1,0,...,0.0,0.0,1.0,0,66.0,1.0,3,0.0,2.0,1.0
44959,zieglbr01,2016,1,ARI,NL,2,3,36,0,0,...,5.0,0.0,2.0,0,165.0,30.0,13,1.0,1.0,10.0
44960,zieglbr01,2016,2,BOS,AL,2,4,33,0,0,...,2.0,1.0,1.0,0,124.0,12.0,8,1.0,0.0,6.0
44962,zychto01,2016,1,SEA,AL,1,0,12,0,0,...,2.0,0.0,1.0,0,60.0,3.0,6,0.0,1.0,1.0